### ISSUE TITLE
The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-preview1-final' was not found.

### ISSUE THREAD

**Issue by subash774** [nemi-chand/Angular5MultipleFileUpload#1]
Hi,
Thanks for a great example. Although I do have .NET CORE version 2.1, I'm unable to run the project. I get an error of "The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-preview1-final' was not found." Any idea why? 

Thanks in advance

**Comment by nemi-chand** [comment]
Hi, I'm really glad that it was helpful for you. hope you are able to resolve the target framework issue. At time of writing this version '2.1.0-preview1-final' was installed on my machine. so you can change the target framework to 2.1. let me know if you are still facing any issue

**Comment by subash774** [comment]
I tried changing it to 2.1 but still didn't work so I started a project from scratch and moved over the files and folders so now it works perfect. However, I can't seem to upload CSV files of more than a certain size. Any idea why?

**Comment by nemi-chand** [comment]
Great. it should work with 2.1 framework. I will update to 2.1. To upload large files, consider streaming the file upload rather than buffering it. more about streaming upload files read [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads#uploading-large-files-with-streaming)
